image: debian:latest

services: 
  - gradle
  - jdk

desktop:
  script:
    - gradle desktop:build

checkstyle:
  script:
    - ./executeCheckstyleTest.sh

sonar:
  script:
    - gradle sonar
  only:
      - master
